version: "3"
services:
  sentry_tunnel:
    build: .
    image: sentry_tunnel
    ports:
      - 7878:7878
    environment : 
      - TUNNEL_PROJECT_IDS=2
      - TUNNEL_IP=0.0.0.0
      - TUNNEL_PATH=/
